name: Deploy Star Wars REST API

on:
  push:
    branches:
      - "main"
    paths:
      - "src/RestApi/StarWarsApi"
      - ".github/workflows/swRestApi.yml"
  workflow_dispatch:
    
env:
  AZURE_WEBAPP_PACKAGE_PATH: package
  AZURE_REST_API_DIRECTORY: ./src/RestApi/StarWarsApi

jobs:

  build-deploy-rest-api:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Setup Dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        working-directory: ${{ env.AZURE_REST_API_DIRECTORY }}          

      - name: Seed database
        run: |
          cnxString='Server=tcp:${{ secrets.SQLSERVER_NAME }}.database.windows.net,1433;Initial Catalog=${{ secrets.DATABASE_NAME }};Persist Security Info=False;User ID=${{ secrets.ADMINISTRATOR_LOGIN }};Password=${{ secrets.ADMINISTRATOR_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
          dotnet run seeddata "Server=DESKTOP-I4VE6ON;Database=StarWarsDb;Trusted_Connection=True;"
        working-directory: ${{ env.AZURE_REST_API_DIRECTORY }}                    

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.STARWARS_REST_API_NAME }}         
          package: '${{ env.AZURE_REST_API_DIRECTORY}}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'                      
